version: '3'
services:
  web:
    build: .
    environment:
      - VIRTUAL_ENV=/env
      - PATH=/env/bin:$PATH
    volumes:
    - ./db:/app/db
    - static_volume:/static
    restart: unless-stopped

  nginx:
    image: nginx
    ports: 
      - 9000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
      
